# mtcars : Motor Trend Car Road Tests

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# 데이터 가져오기
path = '../datasets/ML_data/'

raw1 = pd.read_csv(path+'mpg_X_train.csv')
raw2 = pd.read_csv(path+'mpg_X_test.csv')
raw3 = pd.read_csv(path+'mpg_y_train.csv')

X_train = raw1.copy()
X_test = raw2.copy()
y_train = raw3.copy()

print(X_train.shape, X_test.shape, y_train.shape)

(278, 8) (120, 8) (278, 1)


In [3]:
X_train.head(2)

name   mpg  cylinders  displacement  horsepower  \
0  pontiac j2000 se hatchback  31.0          4         112.0        85.0   
1         pontiac safari (sw)  13.0          8         400.0       175.0   

   weight  acceleration  model_year  
0    2575          16.2          82  
1    5140          12.0          71

In [4]:
y_train.head(2)

isUSA
0      1
1      1

In [5]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278 entries, 0 to 277
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          278 non-null    object 
 1   mpg           278 non-null    float64
 2   cylinders     278 non-null    int64  
 3   displacement  278 non-null    float64
 4   horsepower    274 non-null    float64
 5   weight        278 non-null    int64  
 6   acceleration  278 non-null    float64
 7   model_year    278 non-null    int64  
dtypes: float64(4), int64(3), object(1)
memory usage: 17.5+ KB


horsepower에 결측치 4개 존재함.

In [6]:
X_train.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  278.000000  278.000000    278.000000  274.000000   278.000000   
mean    23.732734    5.374101    189.994604  103.383212  2948.464029   
std      7.647295    1.677084    105.471423   38.977911   862.949746   
min     10.000000    3.000000     68.000000   46.000000  1613.000000   
25%     18.000000    4.000000     98.000000   75.000000  2206.250000   
50%     23.000000    4.000000    140.500000   90.000000  2737.500000   
75%     29.000000    6.000000    258.000000  120.000000  3560.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model_year  
count    278.000000  278.000000  
mean      15.580216   76.057554  
std        2.745907    3.605591  
min        8.000000   70.000000  
25%       14.000000   73.000000  
50%       15.500000   76.000000  
75%       17.000000   79.000000  
max       24.800000   82.000000

In [9]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   name          120 non-null    object 
 1   mpg           120 non-null    float64
 2   cylinders     120 non-null    int64  
 3   displacement  120 non-null    float64
 4   horsepower    118 non-null    float64
 5   weight        120 non-null    int64  
 6   acceleration  120 non-null    float64
 7   model_year    120 non-null    int64  
dtypes: float64(4), int64(3), object(1)
memory usage: 7.6+ KB


In [10]:
X_test.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  120.000000  120.000000    120.000000  118.000000   120.000000   
mean    23.009167    5.641667    201.375000  106.991525  3021.300000   
std      8.204026    1.747968    101.418433   37.377377   809.519617   
min      9.000000    3.000000     70.000000   48.000000  1760.000000   
25%     16.000000    4.000000    108.750000   81.000000  2327.500000   
50%     21.800000    6.000000    177.000000   97.000000  2929.500000   
75%     27.525000    8.000000    302.000000  139.750000  3640.000000   
max     44.300000    8.000000    455.000000  225.000000  4906.000000   

       acceleration  model_year  
count    120.000000  120.000000  
mean      15.540000   75.900000  
std        2.796168    3.915923  
min        8.500000   70.000000  
25%       13.500000   72.750000  
50%       15.500000   76.000000  
75%       17.425000   79.000000  
max       24.600000   82.000000

# 데이터 전처리

In [48]:
# SimpleImputer 사용
# 결측치 대체 >> 평균값 !
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

X_train[['horsepower_fillna']] = imputer.fit_transform(X_train[['horsepower']])
X_test[['horsepower_fillna']] = imputer.fit_transform(X_test[['horsepower']])

X_train.isnull().sum(), X_test.isnull().sum()

(name                 0
 mpg                  0
 cylinders            0
 displacement         0
 horsepower           4
 weight               0
 acceleration         0
 model_year           0
 horsepower_fillna    0
 dtype: int64,
 name                 0
 mpg                  0
 cylinders            0
 displacement         0
 horsepower           2
 weight               0
 acceleration         0
 model_year           0
 horsepower_fillna    0
 dtype: int64)

# 필요한 컬럼 추출하기

In [11]:
print(X_train.columns)
X_train.head(2)

Index(['name', 'mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'horsepower_fillna'],
      dtype='object')


name   mpg  cylinders  displacement  horsepower  \
0  pontiac j2000 se hatchback  31.0          4         112.0        85.0   
1         pontiac safari (sw)  13.0          8         400.0       175.0   

   weight  acceleration  model_year  horsepower_fillna  
0    2575          16.2          82               85.0  
1    5140          12.0          71              175.0

In [19]:
# 컬럼 나누기
# 사용하지 않을 컬럼
del_columns = ['name', 'horsepower']
# 숫자형 데이터
col_num = ['mpg', 'cylinders', 'displacement', 'horsepower_fillna', 'weight', 'acceleration', 'model_year']
# 범주형 데이터
col_cat = []
# 종속변수 컬럼
y_col = ['isUSA']

# 데이터 모델링

In [20]:
# 분석 데이터셋 준비
from sklearn.model_selection import train_test_split

# 위에서 나눠준 컬럼을 이용해 진짜 사용할 training set 다시 만들어주기
X_train_use = X_train.drop(columns=del_columns)

# training / validation dataset
X_train_new, X_val, y_train_new, y_val = \
train_test_split(X_train_use, y_train, test_size=0.3, random_state=42)

print(X_train_new.shape, y_train_new.shape, X_val.shape, y_val.shape)

(194, 7) (194, 1) (84, 7) (84, 1)


## 데이터 스케일링

In [21]:
X_train_new.head(2)

mpg  cylinders  displacement  weight  acceleration  model_year  \
38   20.0          6         225.0    3651          17.7          76   
170  20.8          6         200.0    3070          16.7          78   

     horsepower_fillna  
38               100.0  
170               85.0

In [22]:
# 정규화 >> StandardScaler
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaler.fit(X_train_new[col_num])

X_train_new[col_num] = scaler.transform(X_train_new[col_num])
X_val[col_num] = scaler.transform(X_val[col_num])

In [18]:
# 2차원 -> 1차원
y_train_new.values.ravel()

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0], dtype=int64)

In [26]:
# 모델링 - KNN
from sklearn.neighbors import KNeighborsClassifier

# 모델 생성
knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
# 모델 fitting
knn.fit(X_train_new, y_train_new.values.ravel())

KNeighborsClassifier(metric='euclidean')

In [27]:
# 모델링 - 의사결정나무
from sklearn.tree import DecisionTreeClassifier

# 모델 생성
dt = DecisionTreeClassifier(max_depth=10, random_state=42)
# 모델 fitting
dt.fit(X_train_new, y_train_new)

DecisionTreeClassifier(max_depth=10, random_state=42)

## 모델 성능 평가

In [28]:
# KNN 예측
y_val_pred_knn = knn.predict(X_val)
y_val_pred_proba_knn = knn.predict_proba(X_val)

# DT 예측
y_val_pred_proba_dt = dt.predict_proba(X_val)

In [31]:
y_val.values.ravel(), y_val_pred_knn

(array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
        0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
        1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64),
 array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0,
        0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0], dtype=int64))

In [36]:
y_val_pred_proba_knn[:, 1]

array([1. , 0.6, 0.4, 1. , 0.6, 1. , 0. , 1. , 0.2, 1. , 0.6, 1. , 1. ,
       0.8, 0.6, 1. , 1. , 0.2, 0. , 1. , 1. , 0. , 0.2, 1. , 0.2, 0.8,
       0.2, 0.4, 0.4, 1. , 1. , 1. , 0.8, 0.4, 0. , 1. , 1. , 1. , 0. ,
       0.4, 0.8, 0.6, 1. , 1. , 0.4, 0. , 1. , 1. , 1. , 0.6, 0.2, 0.6,
       0.6, 1. , 0.4, 0.8, 1. , 0.2, 0.4, 0.2, 0.4, 1. , 1. , 0.2, 0.2,
       0.8, 1. , 0.8, 0.8, 0.4, 1. , 1. , 0. , 1. , 1. , 0.8, 0.2, 1. ,
       1. , 1. , 1. , 0.2, 0.4, 0.2])

In [38]:
# ROC-AUC
from sklearn.metrics import roc_auc_score

score_knn = roc_auc_score(y_val, y_val_pred_proba_knn[:, 1])
score_dt = roc_auc_score(y_val, y_val_pred_proba_dt[:, 1])

print(score_knn, score_dt)

0.9346064814814815 0.8506944444444445


In [45]:
best_model = None
best_score = 0

for i in range(2, 10):
    model = KNeighborsClassifier(n_neighbors=i, metric='euclidean')
    model.fit(X_train_new, y_train_new.values.ravel())
    y_val_pred_proba = model.predict_proba(X_val)

    score = roc_auc_score(y_val, y_val_pred_proba[:, 1])
    print(f'{i}개의 이웃일 때의 점수 : {score}')

    if best_score <= score:
        best_score = score
        best_model = model

2개의 이웃일 때의 점수 : 0.8634259259259259
3개의 이웃일 때의 점수 : 0.8900462962962963
4개의 이웃일 때의 점수 : 0.9221643518518519
5개의 이웃일 때의 점수 : 0.9346064814814815
6개의 이웃일 때의 점수 : 0.933449074074074
7개의 이웃일 때의 점수 : 0.9293981481481481
8개의 이웃일 때의 점수 : 0.9302662037037037
9개의 이웃일 때의 점수 : 0.9337384259259259


In [46]:
print(best_model, best_score)

KNeighborsClassifier(metric='euclidean') 0.9346064814814815


In [49]:
X_test_new = X_test.drop(columns=del_columns)
X_test_new[col_num] = scaler.transform(X_test_new[col_num])

best_model.predict_proba(X_test_new)

array([[0.4, 0.6],
       [0.2, 0.8],
       [0. , 1. ],
       [0. , 1. ],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.8, 0.2],
       [0.2, 0.8],
       [0.6, 0.4],
       [0.4, 0.6],
       [0. , 1. ],
       [0.6, 0.4],
       [0. , 1. ],
       [0.4, 0.6],
       [0.8, 0.2],
       [0.8, 0.2],
       [0. , 1. ],
       [0. , 1. ],
       [0.8, 0.2],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0. , 1. ],
       [0.6, 0.4],
       [0.8, 0.2],
       [0. , 1. ],
       [0. , 1. ],
       [0.8, 0.2],
       [0.8, 0.2],
       [0.8, 0.2],
       [0.4, 0.6],
       [0.2, 0.8],
       [0. , 1. ],
       [0.2, 0.8],
       [0.4, 0.6],
       [0. , 1. ],
       [1. , 0. ],
       [0.2, 0.8],
       [0. , 1. ],
       [1. , 0. ],
       [1. , 0. ],
       [0.6, 0.4],
       [0.6, 0.4],
       [0.4, 0.6],
       [0.8, 0.2],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ],
       [1. , 0. ],
       [0.8, 0.2],
       [0. ,

---

# Penguin

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [52]:
# 데이터 준비
path = '../datasets/ML_data/'

X_train_raw = pd.read_csv(path+'penguin_X_train.csv')
X_test_raw = pd.read_csv(path+'penguin_X_test.csv')
y_train_raw = pd.read_csv(path+'penguin_y_train.csv')

X_train = X_train_raw.copy()
X_test = X_test_raw.copy()
y_train = y_train_raw.copy()

print(X_train.shape, X_test.shape, y_train.shape)

(240, 6) (101, 6) (240, 1)


In [53]:
X_train.head(2)

species     island     sex  bill_length_mm  bill_depth_mm  flipper_length_mm
0  Adelie  Torgersen     NaN            42.0           20.2              190.0
1  Gentoo     Biscoe  FEMALE            43.5           15.2              213.0

bill_length : 부리길이, flipper_length : 날개길이

In [54]:
y_train.head(2)

body_mass_g
0       4250.0
1       4650.0

body_mass : 펭귄무게(g)
* 무게를 예측하는 문제

In [55]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 240 entries, 0 to 239
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            240 non-null    object 
 1   island             240 non-null    object 
 2   sex                232 non-null    object 
 3   bill_length_mm     238 non-null    float64
 4   bill_depth_mm      238 non-null    float64
 5   flipper_length_mm  238 non-null    float64
dtypes: float64(3), object(3)
memory usage: 11.4+ KB


In [56]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            101 non-null    object 
 1   island             101 non-null    object 
 2   sex                101 non-null    object 
 3   bill_length_mm     101 non-null    float64
 4   bill_depth_mm      101 non-null    float64
 5   flipper_length_mm  101 non-null    float64
dtypes: float64(3), object(3)
memory usage: 4.9+ KB


X_train : null값 존재함.

In [57]:
X_train.describe(include='all')

species  island   sex  bill_length_mm  bill_depth_mm  flipper_length_mm
count      240     240   232      238.000000     238.000000         238.000000
unique       3       3     2             NaN            NaN                NaN
top     Adelie  Biscoe  MALE             NaN            NaN                NaN
freq       104     118   121             NaN            NaN                NaN
mean       NaN     NaN   NaN       43.948739      17.205462         200.684874
std        NaN     NaN   NaN        5.475004       1.973498          14.110080
min        NaN     NaN   NaN       32.100000      13.200000         172.000000
25%        NaN     NaN   NaN       39.200000      15.700000         190.000000
50%        NaN     NaN   NaN       44.700000      17.300000         197.000000
75%        NaN     NaN   NaN       48.700000      18.700000         213.000000
max        NaN     NaN   NaN       58.000000      21.500000         231.000000

In [59]:
train_data = pd.concat([X_train, y_train], axis=1)
train_data.head(2)

species     island     sex  bill_length_mm  bill_depth_mm  \
0  Adelie  Torgersen     NaN            42.0           20.2   
1  Gentoo     Biscoe  FEMALE            43.5           15.2   

   flipper_length_mm  body_mass_g  
0              190.0       4250.0  
1              213.0       4650.0

In [63]:
# 결측치가 있는 행 확인하기
train_data.loc[train_data.sex.isnull()]

species     island  sex  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen  NaN            42.0           20.2              190.0   
6    Gentoo     Biscoe  NaN            44.5           14.3              216.0   
43   Gentoo     Biscoe  NaN             NaN            NaN                NaN   
66   Adelie  Torgersen  NaN            37.8           17.3              180.0   
88   Gentoo     Biscoe  NaN            47.3           13.8              216.0   
89   Adelie  Torgersen  NaN            37.8           17.1              186.0   
110  Gentoo     Biscoe  NaN            44.5           15.7              217.0   
229  Adelie  Torgersen  NaN             NaN            NaN                NaN   

     body_mass_g  
0         4250.0  
6         4100.0  
43           NaN  
66        3700.0  
88        4725.0  
89        3300.0  
110       4875.0  
229          NaN

In [64]:
train_data.isnull().sum()

species              0
island               0
sex                  8
bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_g          2
dtype: int64

예측하려는 y_train 값에 null 값이 있는데 이것은 제거하는것이 좋을 것 같음.

그런데 sex의 null값은 8개인데 이 중 다른 값이 있는 것은 6개이다. 이것들은 예측해서 넣어줄 수도 있을 것 같은 생각이 든다.

그래서 내가 한다면 sex의 null을 확인한 후, 다른 숫자 데이터로 sex를 예측한 후, 임의로 넣어주고 몸무게를 예측하는 모델을 만들 것 같다.

수업에서 한 것은 제거 ! 왜냐면 결측치의 비율이 0.03밖에 되지 않기 때문 !

In [66]:
train_data_dropna = train_data.dropna().reset_index(drop=True)
train_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 232 entries, 0 to 231
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            232 non-null    object 
 1   island             232 non-null    object 
 2   sex                232 non-null    object 
 3   bill_length_mm     232 non-null    float64
 4   bill_depth_mm      232 non-null    float64
 5   flipper_length_mm  232 non-null    float64
 6   body_mass_g        232 non-null    float64
dtypes: float64(4), object(3)
memory usage: 12.8+ KB


In [70]:
# 독립변수, 종속변수 분리하기
X_train_dropna = train_data_dropna.iloc[:, :-1]
y_train_dropna = train_data_dropna.body_mass_g

* 숫자형 데이터는 스케일링이 필요하고
* 문자형 데이터는 원핫인코딩이 필요하다는 것을 알게 되었음.
* train, test 둘 다 바꿔주어야 한다.

In [71]:
# train, test 합쳐주기
X = pd.concat([X_train_dropna, X_test])
X.head(2)

species     island     sex  bill_length_mm  bill_depth_mm  flipper_length_mm
0  Gentoo     Biscoe  FEMALE            43.5           15.2              213.0
1  Adelie  Torgersen    MALE            42.8           18.5              195.0

In [79]:
# 원핫인코딩할 변수명
col_cat = ['species', 'island', 'sex']
col_num = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm']

In [72]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown='ignore')

encoder.fit(X[col_cat])

X_train_dropna_encoded = encoder.transform(X_train_dropna[col_cat])
X_test_encoded = encoder.transform(X_test[col_cat])

In [74]:
print(X_train_dropna_encoded) # sparse matrix : 희소행렬

  (0, 2)	1.0
  (0, 3)	1.0
  (0, 6)	1.0
  (1, 0)	1.0
  (1, 5)	1.0
  (1, 7)	1.0
  (2, 1)	1.0
  (2, 4)	1.0
  (2, 7)	1.0
  (3, 2)	1.0
  (3, 3)	1.0
  (3, 7)	1.0
  (4, 0)	1.0
  (4, 4)	1.0
  (4, 6)	1.0
  (5, 2)	1.0
  (5, 3)	1.0
  (5, 7)	1.0
  (6, 2)	1.0
  (6, 3)	1.0
  (6, 6)	1.0
  (7, 0)	1.0
  (7, 5)	1.0
  (7, 6)	1.0
  (8, 2)	1.0
  :	:
  (223, 6)	1.0
  (224, 2)	1.0
  (224, 3)	1.0
  (224, 7)	1.0
  (225, 0)	1.0
  (225, 4)	1.0
  (225, 7)	1.0
  (226, 1)	1.0
  (226, 4)	1.0
  (226, 7)	1.0
  (227, 1)	1.0
  (227, 4)	1.0
  (227, 6)	1.0
  (228, 2)	1.0
  (228, 3)	1.0
  (228, 7)	1.0
  (229, 0)	1.0
  (229, 5)	1.0
  (229, 6)	1.0
  (230, 1)	1.0
  (230, 4)	1.0
  (230, 6)	1.0
  (231, 2)	1.0
  (231, 3)	1.0
  (231, 6)	1.0


In [75]:
# todense() : 밀집행렬 dense matrix
X_train_dropna_encoded.todense()

matrix([[0., 0., 1., ..., 0., 1., 0.],
        [1., 0., 0., ..., 1., 0., 1.],
        [0., 1., 0., ..., 0., 0., 1.],
        ...,
        [1., 0., 0., ..., 1., 1., 0.],
        [0., 1., 0., ..., 0., 1., 0.],
        [0., 0., 1., ..., 0., 1., 0.]])

In [76]:
encoder.get_feature_names_out()

array(['species_Adelie', 'species_Chinstrap', 'species_Gentoo',
       'island_Biscoe', 'island_Dream', 'island_Torgersen', 'sex_FEMALE',
       'sex_MALE'], dtype=object)

In [82]:
# 'X_train_dropna' DF와 합쳐주기
X_train_final = pd.concat([pd.DataFrame(X_train_dropna_encoded.todense(), columns=encoder.get_feature_names_out()), X_train_dropna[col_num]], axis=1)
X_test_final = pd.concat([pd.DataFrame(X_test_encoded.todense(), columns=encoder.get_feature_names_out()), X_test[col_num]], axis=1)

print(X_train_final.shape, X_test_final.shape)

(232, 11) (101, 11)


In [83]:
# 데이터 모형 구축하기
from sklearn.model_selection import train_test_split

X_train_new, X_val, y_train_new, y_val = \
train_test_split(X_train_final, y_train_dropna, test_size=0.3, random_state=42)

print(X_train_new.shape, y_train_new.shape, X_val.shape, y_val.shape)

(162, 11) (162,) (70, 11) (70,)


In [84]:
# 숫자형 데이터 스케일링하기
# X_train_new, X_val, X_test_final
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train_new[col_num])

X_train_new[col_num] = scaler.transform(X_train_new[col_num])
X_val[col_num] = scaler.transform(X_val[col_num])
X_test_final[col_num] = scaler.transform(X_test_final[col_num])

In [86]:
# 모델 - 선형회귀
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train_new, y_train_new)

y_val_pred = lr.predict(X_val)

print('BIAS :', lr.intercept_)
print('WEIGHT :', lr.coef_)

BIAS : 3114.2591488243984
WEIGHT : [ -86.71067273 -554.21903603  640.92970876    6.36062312  -11.63903689
    5.27841378 -195.60023602  195.60023602  892.06644989  319.48203134
  969.47314679]


In [89]:
# 가중치 확인
pd.DataFrame(data=lr.coef_, index=X_train_new.columns, columns=['weight']).sort_values(by='weight', ascending=False)

weight
flipper_length_mm  969.473147
bill_length_mm     892.066450
species_Gentoo     640.929709
bill_depth_mm      319.482031
sex_MALE           195.600236
island_Biscoe        6.360623
island_Torgersen     5.278414
island_Dream       -11.639037
species_Adelie     -86.710673
sex_FEMALE        -195.600236
species_Chinstrap -554.219036

In [92]:
# 모델 평가
from sklearn.metrics import mean_squared_error, r2_score

print('MSE : {:.4f}'.format(mean_squared_error(y_val, y_val_pred)))
print('RMSE : {:.4f}'.format(np.sqrt(mean_squared_error(y_val, y_val_pred)))) # mean_squared_error에서 squared=False해주면 루트한 값이 나온다.
print('R2 SCORE : {:.4f}'.format(r2_score(y_val, y_val_pred)))

MSE : 85335.1925
RMSE : 292.1219
R2 SCORE : 0.8568


In [93]:
# test의 예측값 확인
y_pred = lr.predict(X_test_final)
y_pred

array([4163.50844159, 5284.32036751, 4066.75498656, 3494.61594904,
       4635.04063572, 4034.3074739 , 3375.9734752 , 3679.62219441,
       3414.51040167, 3578.34168778, 3366.38665554, 5514.65800452,
       3602.21507436, 3999.49058474, 3802.41527027, 4016.66967746,
       4385.63640607, 3459.85866823, 3613.80026167, 3357.46531639,
       5284.87679332, 4216.65923031, 6020.06654733, 4622.01250961,
       5380.19234268, 5525.80063873, 5565.8265151 , 4317.87218462,
       3316.69841568, 4078.81102867, 4255.88353815, 3412.53965085,
       3402.66719867, 4579.82303422, 3348.57906552, 3519.30383341,
       3241.91313228, 3455.07126676, 3848.95130808, 4960.56702013,
       3511.8136307 , 5621.49741881, 5003.78377613, 4643.87427998,
       5858.0044421 , 3851.30162951, 4753.79532451, 3294.77335072,
       5355.72592265, 4218.0556883 , 4580.77190596, 4740.77966155,
       4171.77485465, 3737.96565103, 3226.3006595 , 4449.73319681,
       4793.44100652, 4565.32678844, 3768.68105657, 4038.24643

In [95]:
# DF 만들기
test_final = X_test_final.copy()

test_final['body_mass_g'] = y_pred
test_final.to_csv(path+'penguin_test_result.csv', index=False)