In [1]:
import numpy as np

In [2]:
# 1차원
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
# 2차원
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data[1])
print(data[0, 1])
print(data[1:3])
print(data[:2, 0])
data

[3 4]
2
[[3 4]
 [5 6]]
[1 3]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
# 0으로 채워진 array
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# 배열의 차원, 크기, 모양
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
# 차원 확인하기
print(array_example.ndim)
# 크기 (= 개수)
print(array_example.size)
# 모양 (shape)
print(array_example.shape)

3
24
(3, 2, 4)


In [14]:
# array 모양 바꾸기
# 1차원 배열
a

# 2차원 (reshape)
print(a.reshape(2, 3))
print(a.reshape(3, 2))

# transpose : 전치 (행과 열을 바꿔줌)
a.reshape(3, 2).T

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


array([[1, 3, 5],
       [2, 4, 6]])

In [16]:
# 기본 연산
ones_row = np.array([[1, 1]])

# 더하기
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [17]:
# 최댓값, 최솟값, 
print(data.max(), data.min())

# 합
print(data.sum())

6 1
21


In [18]:
# 데이터 경로 설정
path = '../datasets/ML_data/'

In [19]:
# 저장할 데이터 생성
csv_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# 저장하기
np.savetxt(path+'new_file.csv', csv_arr)

In [20]:
# 저장된 데이터 불러오기
np.loadtxt(path+'new_file.csv')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])